<?php

use Illuminate\Database\Seeder;
use App\Models\Breed;
use App\Models\Species;

class BreedsTableSeeder extends Seeder
{
    private $akcUrl = 'http://www.akc.org/dog-breeds/';
    private $petmdUrl = 'http://www.petmd.com/dog/breeds/';
    private $unknownUrl = '/breed/no-description/';
    private $catUrl = '/breed/no-description/';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('breeds')->delete();

        $species = Species::where('name', '=', 'Dog')->firstOrFail();

        Breed::create(['species_id' => $species->id, 'name' => 'Affenpinscher', 'description_url' => $this->akcUrl . Urlencode('Affenpinscher'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Afghan Hound', 'description_url' => $this->akcUrl . Urlencode('Afghan Hound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Airedale Terrier', 'description_url' => $this->akcUrl . Urlencode('Airedale Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Akbash', 'description_url' => $this->unknownUrl . Urlencode('Akbash'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Akita', 'description_url' => $this->akcUrl . Urlencode('Akita'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Alaskan Malamute', 'description_url' => $this->akcUrl . Urlencode('Alaskan Malamute'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Bulldog', 'description_url' => $this->petmdUrl . Urlencode('c_dg_american_bulldog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Eskimo Dog', 'description_url' => $this->akcUrl . Urlencode('American Eskimo Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Hairless Terrier', 'description_url' => $this->unknownUrl . Urlencode('American Hairless Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Staffordshire Terrier', 'description_url' => $this->akcUrl . Urlencode('American Staffordshire Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Water Spaniel', 'description_url' => $this->akcUrl . Urlencode('American Water Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Anatolian Shepherd', 'description_url' => $this->akcUrl . Urlencode('Anatolian Shepherd Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Appenzell Mountain Dog', 'description_url' => $this->akcUrl . Urlencode('Appenzeller Sennenhunde'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Australian Cattle Dog (Blue Heeler)', 'description_url' => $this->akcUrl . Urlencode('Australian Cattle Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Australian Kelpie', 'description_url' => $this->unknownUrl . Urlencode('Australian Kelpie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Australian Shepherd', 'description_url' => $this->akcUrl . Urlencode('Australian Shepherd'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Australian Terrier', 'description_url' => $this->akcUrl . Urlencode('Australian Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Basenji', 'description_url' => $this->akcUrl . Urlencode('Basenji'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Basset Hound', 'description_url' => $this->akcUrl . Urlencode('Basset Hound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Beagle', 'description_url' => $this->akcUrl . Urlencode('Beagle'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bearded Collie', 'description_url' => $this->akcUrl . Urlencode('Bearded Collie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Beauceron', 'description_url' => $this->akcUrl . Urlencode('Beauceron'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bedlington Terrier', 'description_url' => $this->akcUrl . Urlencode('Bedlington Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Belgian Shepherd Dog Sheepdog', 'description_url' => $this->akcUrl . Urlencode('Belgian Sheepdog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Belgian Shepherd Laekenois', 'description_url' => $this->akcUrl . Urlencode('Belgian Laekenois'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Belgian Shepherd Malinois', 'description_url' => $this->akcUrl . Urlencode('Belgian Malinois'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Belgian Shepherd Tervuren', 'description_url' => $this->akcUrl . Urlencode('Belgian Tervuren'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bernese Mountain Dog', 'description_url' => $this->akcUrl . Urlencode('Bernese Mountain Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bichon Frise', 'description_url' => $this->akcUrl . Urlencode('Bichon Frise'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Black and Tan Coonhound', 'description_url' => $this->akcUrl . Urlencode('Black and Tan Coonhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Black Labrador Retriever', 'description_url' => $this->akcUrl . Urlencode('Labrador Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Black Mouth Cur', 'description_url' => $this->unknownUrl . Urlencode('Black Mouth Cur'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Black Russian Terrier', 'description_url' => $this->akcUrl . Urlencode('Black Russian Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bloodhound', 'description_url' => $this->akcUrl . Urlencode('Bloodhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Blue Lacy', 'description_url' => $this->unknownUrl . Urlencode('Blue Lacy'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bluetick Coonhound', 'description_url' => $this->akcUrl . Urlencode('Bluetick Coonhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Boerboel', 'description_url' => $this->akcUrl . Urlencode('Boerboel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bolognese', 'description_url' => $this->akcUrl . Urlencode('Bolognese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Border Collie', 'description_url' => $this->akcUrl . Urlencode('Border Collie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Border Terrier', 'description_url' => $this->akcUrl . Urlencode('Border Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Borzoi', 'description_url' => $this->akcUrl . Urlencode('Borzoi'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Boston Terrier', 'description_url' => $this->akcUrl . Urlencode('Boston Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bouvier des Flanders', 'description_url' => $this->akcUrl . Urlencode('Bouvier des Flanders'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Boxer', 'description_url' => $this->akcUrl . Urlencode('Boxer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Boykin Spaniel', 'description_url' => $this->akcUrl . Urlencode('Boykin Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Briard', 'description_url' => $this->akcUrl . Urlencode('Briard'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Brittany Spaniel', 'description_url' => $this->akcUrl . Urlencode('Brittany'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Brussels Griffon', 'description_url' => $this->akcUrl . Urlencode('Brussels Griffon'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bull Terrier', 'description_url' => $this->akcUrl . Urlencode('Bull Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bullmastiff', 'description_url' => $this->akcUrl . Urlencode('Bullmastiff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cairn Terrier', 'description_url' => $this->akcUrl . Urlencode('Cairn Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Canaan Dog', 'description_url' => $this->akcUrl . Urlencode('Canaan Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cane Corso Mastiff', 'description_url' => $this->akcUrl . Urlencode('Cane Corso'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Carolina Dog', 'description_url' => $this->unknownUrl . Urlencode('Carolina Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Catahoula Leopard Dog', 'description_url' => $this->akcUrl . Urlencode('Catahoula Leopard Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cattle Dog', 'description_url' => $this->akcUrl . Urlencode('Cattle Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Caucasian Sheepdog (Caucasian Ovtcharka)', 'description_url' => $this->akcUrl . Urlencode('Caucasian Sheepdog (Caucasian Ovtcharka)'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cavalier King Charles Spaniel', 'description_url' => $this->akcUrl . Urlencode('Cavalier King Charles Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chesapeake Bay Retriever', 'description_url' => $this->akcUrl . Urlencode('Chesapeake Bay Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chihuahua', 'description_url' => $this->akcUrl . Urlencode('Chihuahua'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chinese Crested Dog', 'description_url' => $this->akcUrl . Urlencode('Chinese Crested Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chinese Foo Dog', 'description_url' => $this->akcUrl . Urlencode('Chinese Foo Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chinook', 'description_url' => $this->akcUrl . Urlencode('Chinook'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chocolate Labrador Retriever', 'description_url' => $this->akcUrl . Urlencode('Chocolate Labrador Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chow Chow', 'description_url' => $this->akcUrl . Urlencode('Chow Chow'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cirneco dell\'Etna', 'description_url' => $this->akcUrl . Urlencode('Cirneco dell\'Etna'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Clumber Spaniel', 'description_url' => $this->akcUrl . Urlencode('Clumber Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cockapoo', 'description_url' => $this->akcUrl . Urlencode('Cockapoo'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cocker Spaniel', 'description_url' => $this->akcUrl . Urlencode('Cocker Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Collie', 'description_url' => $this->akcUrl . Urlencode('Collie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Coonhound', 'description_url' => $this->akcUrl . Urlencode('Coonhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Corgi', 'description_url' => $this->akcUrl . Urlencode('Corgi'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Coton de Tulear', 'description_url' => $this->akcUrl . Urlencode('Coton de Tulear'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Curly-Coated Retriever', 'description_url' => $this->akcUrl . Urlencode('Curly-Coated Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dachshund', 'description_url' => $this->akcUrl . Urlencode('Dachshund'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dalmatian', 'description_url' => $this->akcUrl . Urlencode('Dalmatian'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dandi Dinmont Terrier', 'description_url' => $this->akcUrl . Urlencode('Dandi Dinmont Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Doberman Pinscher', 'description_url' => $this->akcUrl . Urlencode('Doberman Pinscher'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dogo Argentino', 'description_url' => $this->akcUrl . Urlencode('Dogo Argentino'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dogue de Bordeaux', 'description_url' => $this->akcUrl . Urlencode('Dogue de Bordeaux'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dutch Shepherd', 'description_url' => $this->akcUrl . Urlencode('Dutch Shepherd'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Bulldog', 'description_url' => $this->akcUrl . Urlencode('English Bulldog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Cocker Spaniel', 'description_url' => $this->akcUrl . Urlencode('English Cocker Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Coonhound', 'description_url' => $this->akcUrl . Urlencode('English Coonhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Pointer', 'description_url' => $this->akcUrl . Urlencode('English Pointer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Setter', 'description_url' => $this->akcUrl . Urlencode('English Setter'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Shepherd', 'description_url' => $this->akcUrl . Urlencode('English Shepherd'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Springer Spaniel', 'description_url' => $this->akcUrl . Urlencode('English Springer Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'English Toy Spaniel', 'description_url' => $this->akcUrl . Urlencode('English Toy Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Entlebucher', 'description_url' => $this->akcUrl . Urlencode('Entlebucher'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Eskimo Dog', 'description_url' => $this->akcUrl . Urlencode('Eskimo Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Feist', 'description_url' => $this->akcUrl . Urlencode('Feist'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Field Spaniel', 'description_url' => $this->akcUrl . Urlencode('Field Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Fila Brasileiro', 'description_url' => $this->akcUrl . Urlencode('Fila Brasileiro'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Finnish Lapphund', 'description_url' => $this->akcUrl . Urlencode('Finnish Lapphund'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Finnish Spitz', 'description_url' => $this->akcUrl . Urlencode('Finnish Spitz'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Flat-coated Retriever', 'description_url' => $this->akcUrl . Urlencode('Flat-coated Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Fox Terrier', 'description_url' => $this->akcUrl . Urlencode('Fox Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Foxhound', 'description_url' => $this->akcUrl . Urlencode('Foxhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'French Bulldog', 'description_url' => $this->akcUrl . Urlencode('French Bulldog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Galgo Spanish Greyhound', 'description_url' => $this->akcUrl . Urlencode('Galgo Spanish Greyhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'German Pinscher', 'description_url' => $this->akcUrl . Urlencode('German Pinscher'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'German Shepherd Dog', 'description_url' => $this->akcUrl . Urlencode('German Shepherd Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'German Shorthaired Pointer', 'description_url' => $this->akcUrl . Urlencode('German Shorthaired Pointer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'German Spitz', 'description_url' => $this->akcUrl . Urlencode('German Spitz'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'German Wirehaired Pointer', 'description_url' => $this->akcUrl . Urlencode('German Wirehaired Pointer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Giant Schnauzer', 'description_url' => $this->akcUrl . Urlencode('Giant Schnauzer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Glen of Imaal Terrier', 'description_url' => $this->akcUrl . Urlencode('Glen of Imaal Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Golden Retriever', 'description_url' => $this->akcUrl . Urlencode('Golden Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Gordon Setter', 'description_url' => $this->akcUrl . Urlencode('Gordon Setter'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Great Dane', 'description_url' => $this->akcUrl . Urlencode('Great Dane'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Great Pyrenees', 'description_url' => $this->akcUrl . Urlencode('Great Pyrenees'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Greater Swiss Mountain Dog', 'description_url' => $this->akcUrl . Urlencode('Greater Swiss Mountain Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Greyhound', 'description_url' => $this->akcUrl . Urlencode('Greyhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Harrier', 'description_url' => $this->akcUrl . Urlencode('Harrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Havanese', 'description_url' => $this->akcUrl . Urlencode('Havanese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Himalayan', 'description_url' => $this->akcUrl . Urlencode('Himalayan'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Hound', 'description_url' => $this->akcUrl . Urlencode('Hound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Hovawart', 'description_url' => $this->akcUrl . Urlencode('Hovawart'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Husky', 'description_url' => $this->akcUrl . Urlencode('Husky'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Ibizan Hound', 'description_url' => $this->akcUrl . Urlencode('Ibizan Hound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Icelandic Sheepdog', 'description_url' => $this->akcUrl . Urlencode('Icelandic Sheepdog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Illyrian Sheepdog', 'description_url' => $this->akcUrl . Urlencode('Illyrian Sheepdog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Irish Setter', 'description_url' => $this->akcUrl . Urlencode('Irish Setter'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Irish Terrier', 'description_url' => $this->akcUrl . Urlencode('Irish Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Irish Water Spaniel', 'description_url' => $this->akcUrl . Urlencode('Irish Water Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Irish Wolfhound', 'description_url' => $this->akcUrl . Urlencode('Irish Wolfhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Italian Greyhound', 'description_url' => $this->akcUrl . Urlencode('Italian Greyhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Italian Spinone', 'description_url' => $this->akcUrl . Urlencode('Italian Spinone'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Jack Russell Terrier', 'description_url' => $this->akcUrl . Urlencode('Jack Russell Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Jack Russell Terrier (Parson Russell Terrier)', 'description_url' => $this->akcUrl . Urlencode('Jack Russell Terrier (Parson Russell Terrier)'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Japanese Chin', 'description_url' => $this->akcUrl . Urlencode('Japanese Chin'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Jindo', 'description_url' => $this->akcUrl . Urlencode('Jindo'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Kai Dog', 'description_url' => $this->akcUrl . Urlencode('Kai Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Karelian Bear Dog', 'description_url' => $this->akcUrl . Urlencode('Karelian Bear Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Keeshond', 'description_url' => $this->akcUrl . Urlencode('Keeshond'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Kerry Blue Terrier', 'description_url' => $this->akcUrl . Urlencode('Kerry Blue Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Kishu', 'description_url' => $this->akcUrl . Urlencode('Kishu'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Klee Kai', 'description_url' => $this->akcUrl . Urlencode('Klee Kai'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Komondor', 'description_url' => $this->akcUrl . Urlencode('Komondor'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Kuvasz', 'description_url' => $this->akcUrl . Urlencode('Kuvasz'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Kyi Leo', 'description_url' => $this->akcUrl . Urlencode('Kyi Leo'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Labrador Retriever', 'description_url' => $this->akcUrl . Urlencode('Labrador Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Lakeland Terrier', 'description_url' => $this->akcUrl . Urlencode('Lakeland Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Lancashire Heeler', 'description_url' => $this->akcUrl . Urlencode('Lancashire Heeler'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Leonberger', 'description_url' => $this->akcUrl . Urlencode('Leonberger'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Lhasa Apso', 'description_url' => $this->akcUrl . Urlencode('Lhasa Apso'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Lowchen', 'description_url' => $this->akcUrl . Urlencode('Lowchen'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Maltese', 'description_url' => $this->akcUrl . Urlencode('Maltese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Manchester Terrier', 'description_url' => $this->akcUrl . Urlencode('Manchester Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Maremma Sheepdog', 'description_url' => $this->akcUrl . Urlencode('Maremma Sheepdog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Mastiff', 'description_url' => $this->akcUrl . Urlencode('Mastiff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'McNab', 'description_url' => $this->akcUrl . Urlencode('McNab'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Miniature Pinscher', 'description_url' => $this->akcUrl . Urlencode('Miniature Pinscher'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Mountain Cur', 'description_url' => $this->akcUrl . Urlencode('Mountain Cur'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Mountain Dog', 'description_url' => $this->akcUrl . Urlencode('Mountain Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Munsterlander', 'description_url' => $this->akcUrl . Urlencode('Munsterlander'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Neapolitan Mastiff', 'description_url' => $this->akcUrl . Urlencode('Neapolitan Mastiff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'New Guinea Singing Dog', 'description_url' => $this->akcUrl . Urlencode('New Guinea Singing Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Newfoundland Dog', 'description_url' => $this->akcUrl . Urlencode('Newfoundland Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Norfolk Terrier', 'description_url' => $this->akcUrl . Urlencode('Norfolk Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Norwegian Buhund', 'description_url' => $this->akcUrl . Urlencode('Norwegian Buhund'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Norwegian Elkhound', 'description_url' => $this->akcUrl . Urlencode('Norwegian Elkhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Norwegian Lundehund', 'description_url' => $this->akcUrl . Urlencode('Norwegian Lundehund'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Norwich Terrier', 'description_url' => $this->akcUrl . Urlencode('Norwich Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Nova Scotia Duck-Tolling Retriever', 'description_url' => $this->akcUrl . Urlencode('Nova Scotia Duck-Tolling Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Old English Sheepdog', 'description_url' => $this->akcUrl . Urlencode('Old English Sheepdog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Oriental Tabby', 'description_url' => $this->akcUrl . Urlencode('Oriental Tabby'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Otterhound', 'description_url' => $this->akcUrl . Urlencode('Otterhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Papillon', 'description_url' => $this->akcUrl . Urlencode('Papillon'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Patterdale Terrier (Fell Terrier)', 'description_url' => $this->akcUrl . Urlencode('Patterdale Terrier (Fell Terrier)'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pekingese', 'description_url' => $this->akcUrl . Urlencode('Pekingese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Peruvian Inca Orchid', 'description_url' => $this->akcUrl . Urlencode('Peruvian Inca Orchid'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Petit Basset Griffon Vendeen', 'description_url' => $this->akcUrl . Urlencode('Petit Basset Griffon Vendeen'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pharaoh Hound', 'description_url' => $this->akcUrl . Urlencode('Pharaoh Hound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pit Bull Terrier', 'description_url' => $this->akcUrl . Urlencode('Pit Bull Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Plott Hound', 'description_url' => $this->akcUrl . Urlencode('Plott Hound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Podengo Portugueso', 'description_url' => $this->akcUrl . Urlencode('Podengo Portugueso'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pointer', 'description_url' => $this->akcUrl . Urlencode('Pointer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Polish Lowland Sheepdog', 'description_url' => $this->akcUrl . Urlencode('Polish Lowland Sheepdog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pomeranian', 'description_url' => $this->akcUrl . Urlencode('Pomeranian'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Poodle', 'description_url' => $this->akcUrl . Urlencode('Poodle'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Poodle, Miniature', 'description_url' => $this->akcUrl . Urlencode('Poodle, Miniature'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Poodle, Toy', 'description_url' => $this->akcUrl . Urlencode('Poodle, Toy'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Portuguese Water Dog', 'description_url' => $this->akcUrl . Urlencode('Portuguese Water Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Presa Canario', 'description_url' => $this->akcUrl . Urlencode('Presa Canario'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pug', 'description_url' => $this->akcUrl . Urlencode('Pug'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Puli', 'description_url' => $this->akcUrl . Urlencode('Puli'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pumi', 'description_url' => $this->akcUrl . Urlencode('Pumi'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Rat Terrier', 'description_url' => $this->akcUrl . Urlencode('Rat Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Redbone Coonhound', 'description_url' => $this->akcUrl . Urlencode('Redbone Coonhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Retriever', 'description_url' => $this->akcUrl . Urlencode('Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Rhodesian Ridgeback', 'description_url' => $this->akcUrl . Urlencode('Rhodesian Ridgeback'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Rottweiler', 'description_url' => $this->akcUrl . Urlencode('Rottweiler'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Saint Bernard St. Bernard', 'description_url' => $this->akcUrl . Urlencode('Saint Bernard St. Bernard'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Saluki', 'description_url' => $this->akcUrl . Urlencode('Saluki'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Samoyed', 'description_url' => $this->akcUrl . Urlencode('Samoyed'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Sarplaninac', 'description_url' => $this->akcUrl . Urlencode('Sarplaninac'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Schipperke', 'description_url' => $this->akcUrl . Urlencode('Schipperke'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Schnauzer', 'description_url' => $this->akcUrl . Urlencode('Schnauzer'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Scottish Deerhound', 'description_url' => $this->akcUrl . Urlencode('Scottish Deerhound'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Scottish Terrier Scottie', 'description_url' => $this->akcUrl . Urlencode('Scottish Terrier Scottie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Sealyham Terrier', 'description_url' => $this->akcUrl . Urlencode('Sealyham Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Setter', 'description_url' => $this->akcUrl . Urlencode('Setter'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Shar Pei', 'description_url' => $this->akcUrl . Urlencode('Shar Pei'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Sheep Dog', 'description_url' => $this->akcUrl . Urlencode('Sheep Dog'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Shepherd', 'description_url' => $this->akcUrl . Urlencode('Shepherd'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Shetland Sheepdog Sheltie', 'description_url' => $this->akcUrl . Urlencode('Shetland Sheepdog Sheltie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Shiba Inu', 'description_url' => $this->akcUrl . Urlencode('Shiba Inu'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Shih Tzu', 'description_url' => $this->akcUrl . Urlencode('Shih Tzu'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Siberian Husky', 'description_url' => $this->akcUrl . Urlencode('Siberian Husky'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Silky Terrier', 'description_url' => $this->akcUrl . Urlencode('Silky Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Skye Terrier', 'description_url' => $this->akcUrl . Urlencode('Skye Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Sloughi', 'description_url' => $this->akcUrl . Urlencode('Sloughi'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Smooth Fox Terrier', 'description_url' => $this->akcUrl . Urlencode('Smooth Fox Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'South Russian Ovtcharka', 'description_url' => $this->akcUrl . Urlencode('South Russian Ovtcharka'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Spaniel', 'description_url' => $this->akcUrl . Urlencode('Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Spitz', 'description_url' => $this->akcUrl . Urlencode('Spitz'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Staffordshire Bull Terrier', 'description_url' => $this->akcUrl . Urlencode('Staffordshire Bull Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Standard Poodle', 'description_url' => $this->akcUrl . Urlencode('Standard Poodle'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Sussex Spaniel', 'description_url' => $this->akcUrl . Urlencode('Sussex Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Swedish Vallhund', 'description_url' => $this->akcUrl . Urlencode('Swedish Vallhund'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Terrier', 'description_url' => $this->akcUrl . Urlencode('Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Thai Ridgeback', 'description_url' => $this->akcUrl . Urlencode('Thai Ridgeback'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tibetan Mastiff', 'description_url' => $this->akcUrl . Urlencode('Tibetan Mastiff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tibetan Spaniel', 'description_url' => $this->akcUrl . Urlencode('Tibetan Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tibetan Terrier', 'description_url' => $this->akcUrl . Urlencode('Tibetan Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tosa Inu', 'description_url' => $this->akcUrl . Urlencode('Tosa Inu'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Toy Fox Terrier', 'description_url' => $this->akcUrl . Urlencode('Toy Fox Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Toy Terrier', 'description_url' => $this->akcUrl . Urlencode('Toy Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tuxedo', 'description_url' => $this->akcUrl . Urlencode('Tuxedo'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Vizsla', 'description_url' => $this->akcUrl . Urlencode('Vizsla'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Weimaraner', 'description_url' => $this->akcUrl . Urlencode('Weimaraner'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Welsh Corgi', 'description_url' => $this->akcUrl . Urlencode('Welsh Corgi'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Welsh Springer Spaniel', 'description_url' => $this->akcUrl . Urlencode('Welsh Springer Spaniel'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Welsh Terrier', 'description_url' => $this->akcUrl . Urlencode('Welsh Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'West Highland White Terrier Westie', 'description_url' => $this->akcUrl . Urlencode('West Highland White Terrier Westie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Wheaten Terrier', 'description_url' => $this->akcUrl . Urlencode('Wheaten Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Whippet', 'description_url' => $this->akcUrl . Urlencode('Whippet'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'White German Shepherd', 'description_url' => $this->akcUrl . Urlencode('White German Shepherd'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Wire Fox Terrier', 'description_url' => $this->akcUrl . Urlencode('Wire Fox Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Wire-haired Pointing Griffon', 'description_url' => $this->akcUrl . Urlencode('Wire-haired Pointing Griffon'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Wirehaired Terrier', 'description_url' => $this->akcUrl . Urlencode('Wirehaired Terrier'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Xoloitzcuintle (Mexican Hairless)', 'description_url' => $this->akcUrl . Urlencode('xoloitzuintli)'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Yellow Labrador Retriever', 'description_url' => $this->akcUrl . Urlencode('Yellow Labrador Retriever'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Yorkie, Yorkshire Terrier', 'description_url' => $this->akcUrl . Urlencode('Yorkie, Yorkshire Terrier'),]);

        $species = Species::where('name', '=', 'Cat')->firstOrFail();

        Breed::create(['species_id' => $species->id, 'name' => 'Abyssinian', 'description_url' => $this->catUrl . Urlencode('Abyssinian'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Curl', 'description_url' => $this->catUrl . Urlencode('American Curl'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Shorthair', 'description_url' => $this->catUrl . Urlencode('American Shorthair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'American Wirehair', 'description_url' => $this->catUrl . Urlencode('American Wirehair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Applehead Siamese', 'description_url' => $this->catUrl . Urlencode('Applehead Siamese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Balinese', 'description_url' => $this->catUrl . Urlencode('Balinese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bengal', 'description_url' => $this->catUrl . Urlencode('Bengal'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Birman', 'description_url' => $this->catUrl . Urlencode('Birman'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bobtail', 'description_url' => $this->catUrl . Urlencode('Bobtail'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Bombay', 'description_url' => $this->catUrl . Urlencode('Bombay'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'British Shorthair', 'description_url' => $this->catUrl . Urlencode('British Shorthair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Burmese', 'description_url' => $this->catUrl . Urlencode('Burmese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Burmilla', 'description_url' => $this->catUrl . Urlencode('Burmilla'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Calico', 'description_url' => $this->catUrl . Urlencode('Calico'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Canadian Hairless', 'description_url' => $this->catUrl . Urlencode('Canadian Hairless'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chartreux', 'description_url' => $this->catUrl . Urlencode('Chartreux'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chausie', 'description_url' => $this->catUrl . Urlencode('Chausie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Chinchilla', 'description_url' => $this->catUrl . Urlencode('Chinchilla'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cornish Rex', 'description_url' => $this->catUrl . Urlencode('Cornish Rex'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Cymric', 'description_url' => $this->catUrl . Urlencode('Cymric'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Devon Rex', 'description_url' => $this->catUrl . Urlencode('Devon Rex'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dilute Calico', 'description_url' => $this->catUrl . Urlencode('Dilute Calico'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Dilute Tortoiseshell', 'description_url' => $this->catUrl . Urlencode('Dilute Tortoiseshell'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair - brown', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair - brown'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair - buff', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair - buff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair - buff and white', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair - buff and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair - gray and white', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair - gray and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair - orange', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair - orange'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair - orange and white', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair - orange and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair-black', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair-black'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair-black and white', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair-black and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair-gray', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair-gray'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Long Hair-white', 'description_url' => $this->catUrl . Urlencode('Domestic Long Hair-white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair - brown', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair - brown'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair - buff', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair - buff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair - buff and white', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair - buff and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair - gray and white', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair - gray and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair - orange and white', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair - orange and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair-black', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair-black'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair-black and white', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair-black and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair-gray', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair-gray'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair-orange', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair-orange'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Medium Hair-white', 'description_url' => $this->catUrl . Urlencode('Domestic Medium Hair-white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair - brown', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair - brown'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair - buff', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair - buff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair - buff and white', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair - buff and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair - gray and white', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair - gray and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair - orange and white', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair - orange and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair-black', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair-black'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair-black and white', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair-black and white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair-gray', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair-gray'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair-mitted', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair-mitted'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair-orange', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair-orange'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Domestic Short Hair-white', 'description_url' => $this->catUrl . Urlencode('Domestic Short Hair-white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Egyptian Mau', 'description_url' => $this->catUrl . Urlencode('Egyptian Mau'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Exotic Shorthair', 'description_url' => $this->catUrl . Urlencode('Exotic Shorthair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Extra-Toes Cat (Hemingway Polydactyl)', 'description_url' => $this->catUrl . Urlencode('Extra-Toes Cat (Hemingway Polydactyl)'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Havana', 'description_url' => $this->catUrl . Urlencode('Havana'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Japanese Bobtail', 'description_url' => $this->catUrl . Urlencode('Japanese Bobtail'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Javanese', 'description_url' => $this->catUrl . Urlencode('Javanese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Korat', 'description_url' => $this->catUrl . Urlencode('Korat'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'LaPerm', 'description_url' => $this->catUrl . Urlencode('LaPerm'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Maine Coon', 'description_url' => $this->catUrl . Urlencode('Maine Coon'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Manx', 'description_url' => $this->catUrl . Urlencode('Manx'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Munchkin', 'description_url' => $this->catUrl . Urlencode('Munchkin'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Nebelung', 'description_url' => $this->catUrl . Urlencode('Nebelung'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Norwegian Forest Cat', 'description_url' => $this->catUrl . Urlencode('Norwegian Forest Cat'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Ocicat', 'description_url' => $this->catUrl . Urlencode('Ocicat'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Oriental Long Hair', 'description_url' => $this->catUrl . Urlencode('Oriental Long Hair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Oriental Short Hair', 'description_url' => $this->catUrl . Urlencode('Oriental Short Hair'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Persian', 'description_url' => $this->catUrl . Urlencode('Persian'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Pixie-Bob', 'description_url' => $this->catUrl . Urlencode('Pixie-Bob'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Ragamuffin', 'description_url' => $this->catUrl . Urlencode('Ragamuffin'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Ragdoll', 'description_url' => $this->catUrl . Urlencode('Ragdoll'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Russian Blue', 'description_url' => $this->catUrl . Urlencode('Russian Blue'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Scottish Fold', 'description_url' => $this->catUrl . Urlencode('Scottish Fold'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Selkirk Rex', 'description_url' => $this->catUrl . Urlencode('Selkirk Rex'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Siamese', 'description_url' => $this->catUrl . Urlencode('Siamese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Siberian', 'description_url' => $this->catUrl . Urlencode('Siberian'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Silver', 'description_url' => $this->catUrl . Urlencode('Silver'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Singapura', 'description_url' => $this->catUrl . Urlencode('Singapura'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Snowshoe', 'description_url' => $this->catUrl . Urlencode('Snowshoe'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Somali', 'description_url' => $this->catUrl . Urlencode('Somali'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Sphynx (hairless cat)', 'description_url' => $this->catUrl . Urlencode('Sphynx (hairless cat)'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby', 'description_url' => $this->catUrl . Urlencode('Tabby'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby - black', 'description_url' => $this->catUrl . Urlencode('Tabby - black'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby - Brown', 'description_url' => $this->catUrl . Urlencode('Tabby - Brown'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby - buff', 'description_url' => $this->catUrl . Urlencode('Tabby - buff'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby - Grey', 'description_url' => $this->catUrl . Urlencode('Tabby - Grey'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby - Orange', 'description_url' => $this->catUrl . Urlencode('Tabby - Orange'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tabby - white', 'description_url' => $this->catUrl . Urlencode('Tabby - white'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tiger', 'description_url' => $this->catUrl . Urlencode('Tiger'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tonkinese', 'description_url' => $this->catUrl . Urlencode('Tonkinese'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Torbie', 'description_url' => $this->catUrl . Urlencode('Torbie'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Tortoiseshell', 'description_url' => $this->catUrl . Urlencode('Tortoiseshell'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Turkish Angora', 'description_url' => $this->catUrl . Urlencode('Turkish Angora'),]);
        Breed::create(['species_id' => $species->id, 'name' => 'Turkish Van', 'description_url' => $this->catUrl . Urlencode('Turkish Van'),]);
    }
}
